//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocStatus
    {
        public int DocStatusID { get; set; }
        public int DocTypeID { get; set; }
        public string Description { get; set; }
    
        public virtual DocType DocType { get; set; }
    }
}
