//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTypeAName
    {
        public int DocTypeANameID { get; set; }
        public int DocTypeAInstrumentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public Nullable<short> Age { get; set; }
        public int NameTypeID { get; set; }
    
        public virtual DocTypeAInstrument DocTypeAInstrument { get; set; }
        public virtual NameType NameType { get; set; }
    }
}
