//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocTypeAInstrument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DocTypeAInstrument()
        {
            this.DocTypeANames = new HashSet<DocTypeAName>();
        }
    
        public int DocTypeAInstrumentID { get; set; }
        public int WorkItemID { get; set; }
        public System.DateTime ApplDate { get; set; }
        public Nullable<System.DateTime> MALDate { get; set; }
        public Nullable<System.DateTime> MARDate { get; set; }
        public int DocStatus { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocTypeAName> DocTypeANames { get; set; }
    }
}
