//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IndexerDBEntities : DbContext
    {
        public IndexerDBEntities()
            : base("name=IndexerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DocTypeAInstrument> DocTypeAInstruments { get; set; }
        public virtual DbSet<DocTypeAName> DocTypeANames { get; set; }
        public virtual DbSet<WorkItemImage> WorkItemImages { get; set; }
        public virtual DbSet<WorkItem> WorkItems { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<DocStatus> DocStatuses { get; set; }
        public virtual DbSet<NameType> NameTypes { get; set; }
    }
}
