//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItemImage
    {
        public int WorkItemImageID { get; set; }
        public int WorkItemID { get; set; }
        public string ImageIdentifier { get; set; }
        public string ImagePath { get; set; }
        public string ImageDescription { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual WorkItem WorkItem { get; set; }
    }
}
