//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Indexer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkItem()
        {
            this.DocTypeAInstruments = new HashSet<DocTypeAInstrument>();
            this.WorkItemImages = new HashSet<WorkItemImage>();
        }
    
        public int WorkItemID { get; set; }
        public int DocTypeID { get; set; }
        public string FileNumber { get; set; }
        public string LockedBy { get; set; }
        public Nullable<System.DateTime> LockedOn { get; set; }
        public bool NotWorkable { get; set; }
        public string Notes { get; set; }
        public string CompletedBy { get; set; }
        public Nullable<System.DateTime> CompletedOn { get; set; }
        public string VerifiedBy { get; set; }
        public Nullable<System.DateTime> VerifiedOn { get; set; }
        public Nullable<System.DateTime> ExportedOn { get; set; }
        public string AddedBy { get; set; }
        public System.DateTime AddedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocTypeAInstrument> DocTypeAInstruments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkItemImage> WorkItemImages { get; set; }
        public virtual DocType DocType { get; set; }
    }
}
